version: '3'
services:
   mydbapp:
     build: ./tomcatexo
     ports:
      - "32771:8080"
     depends_on: 
      - db
   db: 
     build: ./postgresexo
     ports:
      - "5432:5432"
     volumes:
      - db_data:/var/lib/postgresql/data
     container_name: db
volumes:
   db_data: 
